cls
Add-Type -AssemblyName System.Web

$federationUrl = "https://signin.aws.amazon.com/federation"

$sessionjson=@"
{
"sessionId": "$env:AWS_ACCESS_KEY_ID",
"sessionKey": "$env:AWS_SECRET_ACCESS_KEY",
"sessionToken": "$env:AWS_SESSION_TOKEN"
}
"@

$sessionString = [System.Web.HttpUtility]::UrlEncode($sessionjson)
$response = Invoke-WebRequest -URI $($federationurl + "?Action=getSigninToken&Session=" + $sessionString)
$responseJSON = ConvertFrom-Json $response
$signintoken = $responseJSON.SigninToken

$url = ($federationurl + "?Action=login&Destination=https%3A%2F%2Fconsole.aws.amazon.com%2F&Issuer=https%3A%2F%2Fexample.com&SigninToken=" + $signintoken)

function New-TemporaryDirectory {
    $parent = [System.IO.Path]::GetTempPath()
    [string] $name = [System.Guid]::NewGuid()
    New-Item -ItemType Directory -Path (Join-Path $parent $name)
}

function Convert-Color
{
<#
.Synopsis
This color converter gives you the hexadecimal values of your RGB colors and vice versa (RGB to HEX)
.Description
This color converter gives you the hexadecimal values of your RGB colors and vice versa (RGB to HEX). Use it to convert your colors and prepare your graphics and HTML web pages.
.Parameter RBG
Enter the Red Green Blue value comma separated. Red: 51 Green: 51 Blue: 204 for example needs to be entered as 51,51,204
.Parameter HEX
 Enter the Hex value to be converted. Do not use the '#' symbol. (Ex: 3333CC converts to Red: 51 Green: 51 Blue: 204)
.Example
.\convert-color -hex FFFFFF
Converts hex value FFFFFF to RGB
 
.Example
.\convert-color -RGB 123,200,255
Converts Red = 123 Green = 200 Blue = 255 to Hex value
  
#>
param( 
[Parameter(ParameterSetName="RGB",Position=0)]
[ValidateScript({$_ -match '^([01]?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])$'})]
$RGB, 
[Parameter(ParameterSetName="HEX", Position=0)] 
[ValidateScript({$_ -match '[A-Fa-f0-9]{6}'})]
[string]
$HEX
) 
    switch ($PsCmdlet.ParameterSetName) 
    { 
    "RGB"  {
    if ($RGB[2] -eq $null)
    {
      Write-error "Value missing. Please enter all three values seperated by comma."
    }
            $red = [convert]::Tostring($RGB[0],16)
            $green = [convert]::Tostring($RGB[1],16)
            $blue  = [convert]::Tostring($RGB[2],16)
            if ($red.Length -eq 1)
            {$red = '0' + $red}
            if ($green.Length -eq 1)
            {$green = '0'+$green}
            if ($blue.Length -eq 1)
            {$blue = '0'+$blue}
            Write-Output " Hex Value = $red$green$blue"
            }
    "HEX"  {$red = $HEX.Remove(2,4)
            $Green = $HEX.Remove(4,2)
            $Green = $Green.remove(0,2)
            $Blue = $hex.Remove(0,4)
            $Red = [convert]::ToInt32($red,16)
            $Green = [convert]::ToInt32($green,16)
            $Blue = [convert]::ToInt32($blue,16)
            Write-Output "$red,$Green,$blue"
            } 
    } 
}

function Create-Rgb-From-String {
    param (
        $input
    )
    $md5 = New-Object -TypeName System.Security.Cryptography.MD5CryptoServiceProvider
    $utf8 = New-Object -TypeName System.Text.UTF8Encoding
    $hash = [System.BitConverter]::ToString($md5.ComputeHash($utf8.GetBytes($input))).Replace("-", "")
    
    Convert-Color -hex $hash.substring(0,6)
}

#try {
  #$chrome = (Get-ItemProperty 'HKLM:\SOFTWARE\Classes\ChromeHTML\shell\open\command').'(Default)'
  $chrome = "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
  $rgb = Create-Rgb-From-String $env:AWS_ACCESS_KEY_ID
  $tempdir = New-TemporaryDirectory
  Start-Process -FilePath "$chrome" -ArgumentList "--user-data-dir=$tempdir --install-autogenerated-theme=$rgb $url"
#}
#catch {
#  Start-Process $url
#}
